[tool.black]
# 最大行長
line-length = 88

# Python バージョン
target-version = ['py311']

# ダブルクォートの統一をスキップ
skip-string-normalization = true

# 除外ファイル・ディレクトリ
extend-exclude = '''
/(
    env
    | env_new
    | __pycache__
    | \.vscode
    | data
    | docs
    | config
    | build
    | dist
    | \.git
)/
'''

[tool.isort]
# Blackとの互換性
profile = "black"
line_length = 88

# インポートの出力形式
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

# セクション順序
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

# 除外パターン
skip = ["env", "env_new", "__pycache__", ".vscode", "data", "docs", "config", "build", "dist", ".git"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503", "E501"]
max-complexity = 10

# [tool.pydocstyle]
# # Google スタイルのdocstring
# convention = "google"
#
# # 除外するエラー
# add-ignore = ["D100", "D104", "D203", "D213"]
#
# # 除外するディレクトリ
# match-dir = "^(?!(env|env_new|__pycache__|vscode|data|docs|config|build|dist|git)).*"
